language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install
  - composer require --dev codacy/coverage

script:
  - composer ci

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
